version = "1"
pallets = ["pallet_timestamp"]
extrinsic = "on_finalize,set"
exclude_pallets = []
exclude_extrinsics = []
all = false
steps = 50
lowest_range_values = []
highest_range_values = []
repeat = 20
external_repeat = 1
json_output = false
no_median_slopes = false
no_min_squares = false
output = "weights.rs"
output_pov_analysis = "median-slopes"
no_verify = false
extra = false
runtime = "tests/runtimes/base_parachain_benchmark.wasm"
allow_missing_host_functions = false
genesis_builder = "Runtime"
genesis_builder_preset = "development"
database_cache_size = 1024
list = false
no_storage_info = false
worst_case_map_values = 1000000
additional_trie_layers = 2
disable_proof_recording = false
skip_parameters = false
skip_confirm = false
no_build = false
