// SPDX-License-Identifier: GPL-3.0

//! Pop-fork integration tests.

#![cfg(feature = "integration-tests")]

use paste::paste;
use pop_fork::rpc_server::test_scenarios::{
	archive as rpc_server_archive, author as rpc_server_author, block, blockchain, builder, chain,
	chain_head as rpc_server_chain_head, chain_spec, executor, local, remote, rpc,
	state as rpc_server_state, system as rpc_server_system, timestamp,
};
use std::{future::Future, pin::Pin};

type ScenarioFuture = Pin<Box<dyn Future<Output = ()>>>;

async fn run_scenario(fut: ScenarioFuture) {
	fut.await;
}

macro_rules! module_scenarios {
	($($module:ident => [$($scenario:ident),+ $(,)?]),+ $(,)?) => {
		paste! {
			$(
				#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
				async fn [<$module _scenarios>]() {
					$(
						run_scenario(Box::pin($module::$scenario())).await;
					)+
				}
			)+
		}
	};
}

module_scenarios!(
	block => [
		child_commits_parent_storage,
		child_creates_block_with_correct_metadata,
		child_storage_inherits_parent_modifications,
		fork_point_with_hash_creates_block_with_correct_metadata,
		fork_point_with_non_existent_hash_returns_error,
		fork_point_with_non_existent_number_returns_error,
		fork_point_with_number_creates_block_with_correct_metadata,
	],
	blockchain => [
		block_body_returns_extrinsics_for_fork_point_from_remote,
		block_body_returns_extrinsics_for_head,
		block_body_returns_extrinsics_for_parent_block,
		block_body_returns_none_for_unknown_hash,
		block_hash_at_returns_hash_for_block_before_fork_point,
		block_hash_at_returns_hash_for_fork_point,
		block_hash_at_returns_hash_for_head,
		block_hash_at_returns_hash_for_parent_block,
		block_hash_at_returns_none_for_future_block,
		block_header_returns_header_for_different_blocks,
		block_header_returns_header_for_fork_point,
		block_header_returns_header_for_head,
		block_header_returns_header_for_historical_block,
		block_header_returns_none_for_unknown_hash,
		block_number_by_hash_returns_none_for_unknown,
		block_number_by_hash_returns_number_for_fork_point,
		block_number_by_hash_returns_number_for_head,
		block_number_by_hash_returns_number_for_historical_block,
		block_number_by_hash_returns_number_for_parent,
		build_block_result_tracks_failed_extrinsics,
		build_block_result_tracks_included_extrinsics,
		build_block_with_signed_transfer_updates_balances,
		build_empty_block_advances_chain,
		build_multiple_empty_blocks_creates_chain,
		call_at_block_does_not_persist_storage,
		call_at_block_executes_at_fork_point,
		call_at_block_executes_at_head,
		call_at_block_executes_at_historical_block,
		call_at_block_executes_at_parent_block,
		call_at_block_returns_none_for_unknown_hash,
		call_executes_runtime_api,
		fork_at_creates_blockchain_at_specific_block,
		fork_at_with_invalid_block_number_fails,
		fork_creates_blockchain_with_correct_fork_point,
		fork_detects_relay_chain_type,
		fork_retrieves_chain_name,
		fork_with_invalid_endpoint_fails,
		head_returns_current_block,
		head_updates_after_building_block,
		storage_at_queries_specific_block,
		storage_returns_none_for_nonexistent_key,
		storage_returns_value_for_existing_key,
		validate_extrinsic_accepts_valid_transfer,
		validate_extrinsic_rejects_garbage,
	],
	builder => [
		apply_extrinsic_before_inherents_fails,
		apply_extrinsic_before_initialize_fails,
		apply_inherents_before_initialize_fails,
		apply_inherents_twice_fails,
		apply_inherents_without_providers_returns_empty,
		create_next_header_includes_digest_items,
		create_next_header_increments_block_number,
		finalize_before_inherents_fails,
		finalize_before_initialize_fails,
		finalize_produces_child_block,
		initialize_succeeds_and_modifies_storage,
		initialize_twice_fails,
		new_creates_builder_with_empty_extrinsics,
	],
	chain => [
		scenario_chain_get_block_hash_returns_head_hash,
		scenario_chain_get_block_hash_returns_none_hash,
		scenario_chain_get_block_hash_without_number_returns_head_hash,
		scenario_chain_get_block_returns_full_block,
		scenario_chain_get_block_returns_head_when_no_hash,
		scenario_chain_get_finalized_head_returns_head_hash,
		scenario_chain_get_header_returns_head_when_no_hash,
		scenario_chain_get_header_returns_number,
		scenario_chain_get_header_returns_valid_header,
	],
	chain_spec => [
		scenario_chain_spec_chain_name_returns_string,
		scenario_chain_spec_genesis_hash_matches_archive,
		scenario_chain_spec_genesis_hash_returns_valid_hex_hash,
		scenario_chain_spec_properties_returns_json_or_null,
	],
	executor => [
		core_initialize_block_modifies_storage,
		core_version_executes_successfully,
		logs_are_captured_during_execution,
		metadata_executes_successfully,
		runtime_version_extracts_version_info,
		storage_changes_persist_across_calls,
		storage_reads_from_accumulated_changes,
		with_config_applies_custom_settings,
	],
	local => [
		commit_empty_modifications,
		commit_multiple_times,
		commit_preserves_modifications,
		commit_validity_ranges_work_properly,
		commit_with_deletions,
		commit_writes_to_cache,
		delete_prefix_adds_to_deleted_prefixes,
		delete_prefix_blocks_parent_reads,
		delete_prefix_removes_matching_keys,
		delete_prefix_with_empty_prefix,
		diff_excludes_prefix_deleted_keys,
		diff_includes_deletions,
		diff_returns_all_modifications,
		diff_returns_empty_initially,
		get_batch_empty_keys,
		get_batch_falls_back_to_parent,
		get_batch_historical_block,
		get_batch_local_overrides_parent,
		get_batch_maintains_order,
		get_batch_mixed_block_scenarios,
		get_batch_mixed_sources,
		get_batch_non_existent_block_returns_none,
		get_batch_retrieves_modified_value_from_fork_history,
		get_batch_retrieves_unmodified_value_from_remote_at_past_forked_block,
		get_batch_returns_local_modifications,
		get_batch_returns_none_for_deleted_prefix,
		get_falls_back_to_parent,
		get_historical_block,
		get_local_overrides_parent,
		get_non_existent_block_returns_none,
		get_retrieves_modified_value_from_fork_history,
		get_retrieves_unmodified_value_from_remote_at_past_forked_block,
		get_returns_local_modification,
		get_returns_none_for_deleted_prefix_if_exact_key_not_found,
		get_returns_none_for_nonexistent_key,
		get_returns_some_for_deleted_prefix_if_exact_key_found_after_deletion,
		has_code_changed_at_returns_false_for_different_block,
		has_code_changed_at_returns_false_for_non_code_modifications,
		has_code_changed_at_returns_false_when_no_code_modified,
		has_code_changed_at_returns_true_when_code_modified,
		has_code_changed_at_tracks_modification_block_correctly,
		is_deleted_exact_match_only,
		is_deleted_returns_false_initially,
		is_deleted_returns_true_after_delete,
		metadata_at_fetches_from_remote_for_pre_fork_blocks,
		metadata_at_returns_metadata_for_future_blocks,
		new_creates_empty_layer,
		next_key_returns_next_key_from_parent,
		next_key_returns_none_when_all_remaining_deleted,
		next_key_returns_none_when_no_more_keys,
		next_key_skips_deleted_prefix,
		next_key_skips_multiple_deleted_keys,
		next_key_with_empty_prefix,
		next_key_with_nonexistent_prefix,
		register_metadata_version_adds_new_version,
		register_metadata_version_respects_block_boundaries,
		set_batch_duplicate_keys_last_wins,
		set_batch_empty_entries,
		set_batch_overwrites_previous_values,
		set_batch_stores_multiple_values,
		set_batch_with_deletions,
		set_overwrites_previous_value,
		set_stores_value,
	],
	remote => [
		accessor_methods,
		fetch_and_cache_block_by_number_caches_block,
		fetch_and_cache_block_by_number_idempotent,
		fetch_and_cache_block_by_number_multiple_blocks,
		fetch_and_cache_block_by_number_non_existent,
		fetch_and_cache_block_by_number_verifies_parent_chain,
		get_batch_fetches_mixed,
		get_batch_uses_cache,
		get_caches_empty_values,
		get_fetches_and_caches,
		layer_is_cloneable,
		prefetch_prefix,
	],
	rpc => [
		connect_to_invalid_endpoint_fails,
		connect_to_node,
		fetch_finalized_head,
		fetch_header,
		fetch_header_non_existent_block_fails,
		fetch_metadata,
		fetch_runtime_code,
		fetch_storage,
		fetch_storage_batch,
		fetch_storage_batch_empty_keys,
		fetch_storage_batch_with_mixed_keys,
		fetch_storage_keys_paged,
		fetch_storage_non_existent_key_returns_none,
		fetch_system_chain,
		fetch_system_properties,
	],
	rpc_server_archive => [
		archive_body_is_idempotent_over_finalized_blocks,
		archive_body_returns_extrinsics_for_valid_hashes,
		archive_body_returns_none_for_unknown_hash,
		archive_call_does_not_persist_storage_changes,
		archive_call_executes_at_specific_block,
		archive_call_executes_runtime_api,
		archive_call_rejects_invalid_hex_hash,
		archive_call_rejects_invalid_hex_parameters,
		archive_call_returns_error_for_invalid_function,
		archive_call_returns_null_for_unknown_block,
		archive_finalized_height_returns_correct_value,
		archive_genesis_hash_returns_valid_hash,
		archive_hash_by_height_returns_hash_at_different_heights,
		archive_hash_by_height_returns_none_for_unknown_height,
		archive_header_is_idempotent_over_finalized_blocks,
		archive_header_rejects_invalid_hex,
		archive_header_returns_header_for_fork_point,
		archive_header_returns_header_for_head_hash,
		archive_header_returns_header_for_parent_block,
		archive_header_returns_none_for_unknown_hash,
		archive_storage_diff_detects_modified_value,
		archive_storage_diff_handles_multiple_items,
		archive_storage_diff_returns_added_for_new_key,
		archive_storage_diff_returns_deleted_for_removed_key,
		archive_storage_diff_returns_empty_for_unchanged_keys,
		archive_storage_diff_returns_error_for_unknown_hash,
		archive_storage_diff_returns_error_for_unknown_previous_hash,
		archive_storage_diff_returns_hash_when_requested,
		archive_storage_diff_uses_parent_when_previous_hash_omitted,
		archive_storage_queries_at_specific_block,
		archive_storage_returns_error_for_unknown_block,
		archive_storage_returns_hash_when_requested,
		archive_storage_returns_none_for_nonexistent_key,
		archive_storage_returns_value_for_existing_key,
	],
	rpc_server_author => [
		author_pending_extrinsics_empty_after_submit,
		author_submit_and_watch_sends_invalid_on_validation_failure,
		author_submit_and_watch_sends_lifecycle_events,
		author_submit_extrinsic_does_not_build_block_on_validation_failure,
		author_submit_extrinsic_invalid_hex,
		author_submit_extrinsic_rejects_garbage_with_error_code,
		author_submit_extrinsic_returns_correct_hash,
	],
	rpc_server_chain_head => [
		follow_returns_subscription_and_initialized_event,
		header_returns_header_for_valid_subscription,
		invalid_subscription_returns_error,
	],
	rpc_server_state => [
		state_get_metadata_at_block_hash,
		state_get_metadata_returns_metadata,
		state_get_runtime_version_at_block_hash,
		state_get_runtime_version_returns_version,
		state_get_storage_at_block_hash,
		state_get_storage_invalid_block_hash_returns_error,
		state_get_storage_invalid_hex_returns_error,
		state_get_storage_returns_none_for_nonexistent_key,
		state_get_storage_returns_value,
	],
	rpc_server_system => [
		account_next_index_invalid_address_returns_error,
		account_next_index_returns_nonce,
		account_next_index_returns_zero_for_nonexistent,
		chain_works,
		health_works,
		name_works,
		properties_returns_json_or_null,
		version_works,
	],
	timestamp => [
		get_slot_duration_falls_back_when_aura_api_unavailable,
		get_slot_duration_from_live_aura_chain,
		get_slot_duration_from_live_babe_chain,
	],
);
