// SPDX-License-Identifier: GPL-3.0

//! Single-entry integration test that executes all pop-fork integration checks sequentially.

#![cfg(feature = "integration-tests")]

#[path = "block.rs"]
mod block;
#[path = "blockchain.rs"]
mod blockchain;
#[path = "builder.rs"]
mod builder;
#[path = "executor.rs"]
mod executor;
#[path = "local.rs"]
mod local;
#[path = "remote.rs"]
mod remote;
#[path = "rpc.rs"]
mod rpc;
#[path = "rpc_server_archive.rs"]
mod rpc_server_archive;
#[path = "rpc_server_author.rs"]
mod rpc_server_author;
#[path = "rpc_server_chain.rs"]
mod rpc_server_chain;
#[path = "rpc_server_chain_head.rs"]
mod rpc_server_chain_head;
#[path = "rpc_server_chain_spec.rs"]
mod rpc_server_chain_spec;
#[path = "rpc_server_state.rs"]
mod rpc_server_state;
#[path = "rpc_server_system.rs"]
mod rpc_server_system;
#[path = "timestamp.rs"]
mod timestamp;

#[tokio::test(flavor = "multi_thread")]
async fn pop_fork_all_integration_tests_single_entry() {
	block::fork_point_with_hash_creates_block_with_correct_metadata().await;
	block::fork_point_with_non_existent_hash_returns_error().await;
	block::fork_point_with_number_creates_block_with_correct_metadata().await;
	block::fork_point_with_non_existent_number_returns_error().await;
	block::child_creates_block_with_correct_metadata().await;
	block::child_commits_parent_storage().await;
	block::child_storage_inherits_parent_modifications().await;
	blockchain::fork_creates_blockchain_with_correct_fork_point().await;
	blockchain::fork_at_creates_blockchain_at_specific_block().await;
	blockchain::fork_with_invalid_endpoint_fails().await;
	blockchain::fork_at_with_invalid_block_number_fails().await;
	blockchain::fork_detects_relay_chain_type().await;
	blockchain::fork_retrieves_chain_name().await;
	blockchain::build_empty_block_advances_chain().await;
	blockchain::build_multiple_empty_blocks_creates_chain().await;
	blockchain::storage_returns_value_for_existing_key().await;
	blockchain::storage_returns_none_for_nonexistent_key().await;
	blockchain::storage_at_queries_specific_block().await;
	blockchain::call_executes_runtime_api().await;
	blockchain::head_returns_current_block().await;
	blockchain::head_updates_after_building_block().await;
	blockchain::build_block_with_signed_transfer_updates_balances().await;
	blockchain::block_body_returns_extrinsics_for_head().await;
	blockchain::block_body_returns_extrinsics_for_parent_block().await;
	blockchain::block_body_returns_extrinsics_for_fork_point_from_remote().await;
	blockchain::block_body_returns_none_for_unknown_hash().await;
	blockchain::block_header_returns_header_for_head().await;
	blockchain::block_header_returns_header_for_different_blocks().await;
	blockchain::block_header_returns_header_for_fork_point().await;
	blockchain::block_header_returns_none_for_unknown_hash().await;
	blockchain::block_header_returns_header_for_historical_block().await;
	blockchain::block_hash_at_returns_hash_for_head().await;
	blockchain::block_hash_at_returns_hash_for_parent_block().await;
	blockchain::block_hash_at_returns_hash_for_fork_point().await;
	blockchain::block_hash_at_returns_hash_for_block_before_fork_point().await;
	blockchain::block_hash_at_returns_none_for_future_block().await;
	blockchain::block_number_by_hash_returns_number_for_head().await;
	blockchain::block_number_by_hash_returns_number_for_parent().await;
	blockchain::block_number_by_hash_returns_number_for_fork_point().await;
	blockchain::block_number_by_hash_returns_none_for_unknown().await;
	blockchain::block_number_by_hash_returns_number_for_historical_block().await;
	blockchain::call_at_block_executes_at_head().await;
	blockchain::call_at_block_executes_at_fork_point().await;
	blockchain::call_at_block_executes_at_parent_block().await;
	blockchain::call_at_block_returns_none_for_unknown_hash().await;
	blockchain::call_at_block_executes_at_historical_block().await;
	blockchain::call_at_block_does_not_persist_storage().await;
	blockchain::validate_extrinsic_accepts_valid_transfer().await;
	blockchain::validate_extrinsic_rejects_garbage().await;
	blockchain::build_block_result_tracks_included_extrinsics().await;
	blockchain::build_block_result_tracks_failed_extrinsics().await;
	builder::new_creates_builder_with_empty_extrinsics().await;
	builder::initialize_succeeds_and_modifies_storage().await;
	builder::initialize_twice_fails().await;
	builder::apply_inherents_without_providers_returns_empty().await;
	builder::apply_inherents_before_initialize_fails().await;
	builder::apply_extrinsic_before_initialize_fails().await;
	builder::finalize_before_initialize_fails().await;
	builder::apply_inherents_twice_fails().await;
	builder::apply_extrinsic_before_inherents_fails().await;
	builder::finalize_before_inherents_fails().await;
	builder::finalize_produces_child_block().await;
	builder::create_next_header_increments_block_number().await;
	builder::create_next_header_includes_digest_items().await;
	executor::core_version_executes_successfully().await;
	executor::metadata_executes_successfully().await;
	executor::with_config_applies_custom_settings().await;
	executor::logs_are_captured_during_execution().await;
	executor::core_initialize_block_modifies_storage().await;
	executor::storage_reads_from_accumulated_changes().await;
	executor::storage_changes_persist_across_calls().await;
	executor::runtime_version_extracts_version_info().await;
	local::new_creates_empty_layer().await;
	local::get_returns_local_modification().await;
	local::get_non_existent_block_returns_none().await;
	local::get_returns_none_for_deleted_prefix_if_exact_key_not_found().await;
	local::get_returns_some_for_deleted_prefix_if_exact_key_found_after_deletion().await;
	local::get_falls_back_to_parent().await;
	local::get_local_overrides_parent().await;
	local::get_returns_none_for_nonexistent_key().await;
	local::get_retrieves_modified_value_from_fork_history().await;
	local::get_retrieves_unmodified_value_from_remote_at_past_forked_block().await;
	local::get_historical_block().await;
	local::set_stores_value().await;
	local::set_overwrites_previous_value().await;
	local::get_batch_empty_keys().await;
	local::get_batch_returns_local_modifications().await;
	local::get_batch_returns_none_for_deleted_prefix().await;
	local::get_batch_falls_back_to_parent().await;
	local::get_batch_local_overrides_parent().await;
	local::get_batch_mixed_sources().await;
	local::get_batch_maintains_order().await;
	local::get_batch_retrieves_modified_value_from_fork_history().await;
	local::get_batch_retrieves_unmodified_value_from_remote_at_past_forked_block().await;
	local::get_batch_historical_block().await;
	local::get_batch_non_existent_block_returns_none().await;
	local::get_batch_mixed_block_scenarios().await;
	local::set_batch_empty_entries().await;
	local::set_batch_stores_multiple_values().await;
	local::set_batch_with_deletions().await;
	local::set_batch_overwrites_previous_values().await;
	local::set_batch_duplicate_keys_last_wins().await;
	local::delete_prefix_removes_matching_keys().await;
	local::delete_prefix_blocks_parent_reads().await;
	local::delete_prefix_adds_to_deleted_prefixes().await;
	local::delete_prefix_with_empty_prefix().await;
	local::is_deleted_returns_false_initially().await;
	local::is_deleted_returns_true_after_delete().await;
	local::is_deleted_exact_match_only().await;
	local::diff_returns_empty_initially().await;
	local::diff_returns_all_modifications().await;
	local::diff_includes_deletions().await;
	local::diff_excludes_prefix_deleted_keys().await;
	local::commit_writes_to_cache().await;
	local::commit_preserves_modifications().await;
	local::commit_with_deletions().await;
	local::commit_empty_modifications().await;
	local::commit_multiple_times().await;
	local::commit_validity_ranges_work_properly().await;
	local::next_key_returns_next_key_from_parent().await;
	local::next_key_returns_none_when_no_more_keys().await;
	local::next_key_skips_deleted_prefix().await;
	local::next_key_skips_multiple_deleted_keys().await;
	local::next_key_returns_none_when_all_remaining_deleted().await;
	local::next_key_with_empty_prefix().await;
	local::next_key_with_nonexistent_prefix().await;
	local::metadata_at_returns_metadata_for_future_blocks().await;
	local::metadata_at_fetches_from_remote_for_pre_fork_blocks().await;
	local::register_metadata_version_adds_new_version().await;
	local::register_metadata_version_respects_block_boundaries().await;
	local::has_code_changed_at_returns_false_when_no_code_modified().await;
	local::has_code_changed_at_returns_false_for_non_code_modifications().await;
	local::has_code_changed_at_returns_true_when_code_modified().await;
	local::has_code_changed_at_returns_false_for_different_block().await;
	local::has_code_changed_at_tracks_modification_block_correctly().await;
	remote::get_fetches_and_caches().await;
	remote::get_caches_empty_values().await;
	remote::get_batch_fetches_mixed().await;
	remote::get_batch_uses_cache().await;
	remote::prefetch_prefix().await;
	remote::layer_is_cloneable().await;
	remote::accessor_methods().await;
	remote::fetch_and_cache_block_by_number_caches_block().await;
	remote::fetch_and_cache_block_by_number_non_existent().await;
	remote::fetch_and_cache_block_by_number_multiple_blocks().await;
	remote::fetch_and_cache_block_by_number_idempotent().await;
	remote::fetch_and_cache_block_by_number_verifies_parent_chain().await;
	rpc::connect_to_node().await;
	rpc::fetch_finalized_head().await;
	rpc::fetch_header().await;
	rpc::fetch_storage().await;
	rpc::fetch_metadata().await;
	rpc::fetch_runtime_code().await;
	rpc::fetch_storage_keys_paged().await;
	rpc::fetch_storage_batch().await;
	rpc::fetch_system_chain().await;
	rpc::fetch_system_properties().await;
	rpc::connect_to_invalid_endpoint_fails().await;
	rpc::fetch_header_non_existent_block_fails().await;
	rpc::fetch_storage_non_existent_key_returns_none().await;
	rpc::fetch_storage_batch_with_mixed_keys().await;
	rpc::fetch_storage_batch_empty_keys().await;
	rpc_server_archive::archive_finalized_height_returns_correct_value().await;
	rpc_server_archive::archive_genesis_hash_returns_valid_hash().await;
	rpc_server_archive::archive_hash_by_height_returns_hash_at_different_heights().await;
	rpc_server_archive::archive_hash_by_height_returns_none_for_unknown_height().await;
	rpc_server_archive::archive_header_returns_header_for_head_hash().await;
	rpc_server_archive::archive_header_returns_none_for_unknown_hash().await;
	rpc_server_archive::archive_header_returns_header_for_fork_point().await;
	rpc_server_archive::archive_header_returns_header_for_parent_block().await;
	rpc_server_archive::archive_header_is_idempotent_over_finalized_blocks().await;
	rpc_server_archive::archive_body_returns_extrinsics_for_valid_hashes().await;
	rpc_server_archive::archive_body_is_idempotent_over_finalized_blocks().await;
	rpc_server_archive::archive_body_returns_none_for_unknown_hash().await;
	rpc_server_archive::archive_call_executes_runtime_api().await;
	rpc_server_archive::archive_call_returns_error_for_invalid_function().await;
	rpc_server_archive::archive_call_returns_null_for_unknown_block().await;
	rpc_server_archive::archive_call_executes_at_specific_block().await;
	rpc_server_archive::archive_call_rejects_invalid_hex_hash().await;
	rpc_server_archive::archive_storage_returns_value_for_existing_key().await;
	rpc_server_archive::archive_storage_returns_none_for_nonexistent_key().await;
	rpc_server_archive::archive_header_rejects_invalid_hex().await;
	rpc_server_archive::archive_call_rejects_invalid_hex_parameters().await;
	rpc_server_archive::archive_call_does_not_persist_storage_changes().await;
	rpc_server_archive::archive_storage_returns_hash_when_requested().await;
	rpc_server_archive::archive_storage_queries_at_specific_block().await;
	rpc_server_archive::archive_storage_returns_error_for_unknown_block().await;
	rpc_server_archive::archive_storage_diff_detects_modified_value().await;
	rpc_server_archive::archive_storage_diff_returns_empty_for_unchanged_keys().await;
	rpc_server_archive::archive_storage_diff_returns_added_for_new_key().await;
	rpc_server_archive::archive_storage_diff_returns_deleted_for_removed_key().await;
	rpc_server_archive::archive_storage_diff_returns_hash_when_requested().await;
	rpc_server_archive::archive_storage_diff_returns_error_for_unknown_hash().await;
	rpc_server_archive::archive_storage_diff_returns_error_for_unknown_previous_hash().await;
	rpc_server_archive::archive_storage_diff_uses_parent_when_previous_hash_omitted().await;
	rpc_server_archive::archive_storage_diff_handles_multiple_items().await;
	rpc_server_author::author_submit_extrinsic_builds_block_immediately().await;
	rpc_server_author::author_pending_extrinsics_empty_after_submit().await;
	rpc_server_author::author_submit_extrinsic_returns_correct_hash().await;
	rpc_server_author::author_submit_extrinsic_invalid_hex().await;
	rpc_server_author::author_submit_and_watch_sends_lifecycle_events().await;
	rpc_server_author::author_submit_extrinsic_rejects_garbage_with_error_code().await;
	rpc_server_author::author_submit_extrinsic_does_not_build_block_on_validation_failure().await;
	rpc_server_author::author_submit_and_watch_sends_invalid_on_validation_failure().await;
	rpc_server_chain::chain_get_block_hash_returns_head_hash().await;
	rpc_server_chain::chain_get_block_hash_returns_none_hash().await;
	rpc_server_chain::chain_get_block_hash_returns_fork_point_hash().await;
	rpc_server_chain::chain_get_block_hash_returns_historical_hash().await;
	rpc_server_chain::chain_get_header_returns_valid_header().await;
	rpc_server_chain::chain_get_header_returns_head_when_no_hash().await;
	rpc_server_chain::chain_get_header_for_fork_point().await;
	rpc_server_chain::chain_get_block_returns_full_block().await;
	rpc_server_chain::chain_get_block_returns_head_when_no_hash().await;
	rpc_server_chain::chain_get_finalized_head_returns_head_hash().await;
	rpc_server_chain::chain_get_finalized_head_updates_after_block().await;
	rpc_server_chain_head::follow_returns_subscription_and_initialized_event().await;
	rpc_server_chain_head::header_returns_header_for_valid_subscription().await;
	rpc_server_chain_head::invalid_subscription_returns_error().await;
	rpc_server_chain_spec::chain_spec_chain_name_returns_string().await;
	rpc_server_chain_spec::chain_spec_genesis_hash_returns_valid_hex_hash().await;
	rpc_server_chain_spec::chain_spec_genesis_hash_matches_archive().await;
	rpc_server_chain_spec::chain_spec_properties_returns_json_or_null().await;
	rpc_server_state::state_get_storage_returns_value().await;
	rpc_server_state::state_get_storage_at_block_hash().await;
	rpc_server_state::state_get_storage_returns_none_for_nonexistent_key().await;
	rpc_server_state::state_get_metadata_returns_metadata().await;
	rpc_server_state::state_get_metadata_at_block_hash().await;
	rpc_server_state::state_get_runtime_version_returns_version().await;
	rpc_server_state::state_get_runtime_version_at_block_hash().await;
	rpc_server_state::state_get_storage_invalid_hex_returns_error().await;
	rpc_server_state::state_get_storage_invalid_block_hash_returns_error().await;
	rpc_server_system::chain_works().await;
	rpc_server_system::name_works().await;
	rpc_server_system::version_works().await;
	rpc_server_system::health_works().await;
	rpc_server_system::chain_spec_chain_name().await;
	rpc_server_system::properties_returns_json_or_null().await;
	rpc_server_system::account_next_index_returns_nonce().await;
	rpc_server_system::account_next_index_returns_zero_for_nonexistent().await;
	rpc_server_system::account_next_index_invalid_address_returns_error().await;
	timestamp::get_slot_duration_falls_back_when_aura_api_unavailable().await;
	timestamp::get_slot_duration_from_live_aura_chain().await;
	timestamp::get_slot_duration_from_live_babe_chain().await;
}
