[general]
# Directories to search for templates, relative to the crate root.
dirs = ["templates"]
# Unless you add a `-` in a block, whitespace characters won't be trimmed.
whitespace = "preserve"
default_syntax = "substrate"

[[syntax]]
name = "substrate"
block_start = "{{"
block_end = "}}"
comment_start = "#{"
comment_end = "}#"
expr_start = "^^"
expr_end = "^^"

