name: Initialize
description: This action initializes a runner for use in other actions.
inputs:
  cache-key:
    description: "The key to be used for the cache"
  git-user:
    required: true
    description: "The user name to be used for git config"

runs:
  using: "composite"
  steps:
    - name: Setup Ubuntu dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y protobuf-compiler

    - name: Free up space on runner
      shell: bash
      run: |
        sudo rm -rf "$AGENT_TOOLSDIRECTORY" /opt/ghc /usr/local/lib/android /usr/local/share/boost 
        sudo rm -rf /usr/local/share/chromium /usr/share/dotnet /usr/share/swift
        sudo docker image prune -af
        sudo apt-get clean
        sudo rm -rf /var/cache/apt/archives /var/lib/apt/lists/*

    - name: Setup git config
      shell: bash
      run: |
        git config --global user.name ${{ inputs.git-user }}
        git config --global user.email ${{ inputs.git-user }}@users.noreply.github.com

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.8
      with:
        cache-on-failure: true
        cache-all-crates: true
        key: ${{ inputs.cache-key }}